from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Protocol, runtime_checkable


@runtime_checkable
class CanvasProtocol(Protocol):
    @property
    def size_pt(self) -> tuple[float, float]: ...
    def place(self, o: dict, dpi: int, resolve_panel: Callable[[dict, int], Path]) -> None: ...
    def save_pdf(self, path: Path) -> None: ...
    def save_png(self, path: Path, dpi: int) -> None: ...
    def save_tiff(self, path: Path, dpi: int) -> dict: ...
    def close(self) -> None: ...
    def __enter__(self) -> CanvasProtocol: ...
    def __exit__(self, *exc: Any) -> None: ...


@runtime_checkable
class PreviewBackend(Protocol):
    backend_name: str

    @property
    def backend_version(self) -> str: ...
    def render_preview_png(self, path: Path, width_px: int, out: Path) -> None: ...


@runtime_checkable
class PdfBackend(Protocol):
    def annotate_asset(
        self, pdf_path: Path, png_path: Path | None, objects: list[dict], dpi: int = 600
    ) -> None: ...
    def compare_png(self, baseline: Path, candidate: Path) -> dict: ...
    def compose(
        self, page_w_mm: float, page_h_mm: float, transparent: bool = False
    ) -> CanvasProtocol: ...
    def coverage_ranges(self) -> dict: ...
    def hex2rgb(self, s: str) -> tuple[float, float, float]: ...
    def missing_glyphs(
        self, s: str, family: object = "serif", bold: bool = False, italic: bool = False
    ) -> list[str]: ...
    def mm2pt(self, mm: float) -> float: ...
    def original_pdf(
        self, src: Path, out: Path, page_pt: tuple[float, float] | None = None
    ) -> dict: ...
    def original_png(
        self, src: Path, out: Path, ppi: int | None, transparent: bool = False
    ) -> dict: ...
    def original_tiff(
        self,
        src: Path,
        out: Path,
        ppi: int | None,
        transparent: bool = False,
        *,
        dpi_meta: float | None = None,
    ) -> dict: ...
    def pdf_fonts(self, path: Path) -> list[str]: ...
    def probe_asset(self, path: Path, kind: str) -> dict: ...
    def render_preview_png(self, path: Path, width_px: int, out: Path) -> None: ...
    def text_plan(
        self, s: str, family: object = "serif", bold: bool = False, italic: bool = False
    ) -> list[tuple[str, str]]: ...
    def text_width(
        self,
        s: str,
        size_pt: float,
        bold: bool = False,
        italic: bool = False,
        family: object = "serif",
    ) -> float: ...
